apiVersion: v1
kind: Pod
metadata:
  name: logstash-elasticsearch
  namespace: kube-system
spec:
  replicas: 1
  containers:
  - name: logstash-elasticsearch
    image: ecr.vip.ebayc3.com/kubernetes/logstash-elasticsearch:2.0.0-u1
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
    env:
      - name: "KUBERNETES_NODE_FQDN"
        value: "{{ grains['fqdn'] }}"
      - name: "ELASTICSEARCH_HOST_PORT"
        value: "{{ pillar.get('elasticsearch_host_port') }}"
      - name: "OS_TENANT_NAME"
        value: "{{ pillar.get('os_tenant_name') }}"
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
  terminationGracePeriodSeconds: 30
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers

