{% set heapster_memory_mb = "300" -%}
{% if pillar['heapster_memory_mb'] is defined -%}
  {% set heapster_memory_mb = pillar['heapster_memory_mb'] -%}
{% endif -%}

apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v10
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v10
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v10
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v10
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
       - image: ecr.vip.ebayc3.com/kubernetes/heapster:99fd84a
         name: heapster
         resources:
           limits:
             cpu: 100m
             memory: {{ heapster_memory_mb }}Mi
         command:
          - /heapster
          - --source=kubernetes:''
          - --sink=elasticsearch:?nodes=http://elasticsearch-logging:9200
          - --stats_resolution=30s
          - --sink_frequency=1m
