scrape_configs:
- job_name: 'kubernetes-cluster'

  # This TLS & bearer token file config is used to connect to the actual scrape
  # endpoints for cluster components. This is separate to discovery auth
  # configuration (`in_cluster` below) because discovery & scraping are two
  # separate concerns in Prometheus.
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  kubernetes_sd_configs:
  - kubernetes_service: 'KUBERNETES_SERVICE'
    in_cluster: true

  relabel_configs:
  - source_labels: [__meta_kubernetes_role]
    action: replace
    regex: ^(.+)$
    target_label: kubernetes_role
    replacement: $1

rule_files:
  - /etc/prometheus/rules.txt
