kind: Service
apiVersion: v1
metadata:
  name: monitoring-prometheus
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Prometheus"
spec: 
  ports: 
    - port: 9090
      targetPort: 9090
  selector: 
    k8s-app: prometheus-server
